name: flutter_encryption_guide
description: "A new Flutter project to demo the process of Taking Encryption Key when User Login for First Time"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
